name: Secret Scan

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3
        with:
          scan: git

      - name: Scan Push or PR Diff
        uses: trufflesecurity/trufflehog@v3
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --only-verified
