name: Secret Scan

on:
  push:
    branches:
      - "**" # Escanear em qualquer branch
  pull_request:
    branches:
      - "**"

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout do c贸digo completo para garantir acesso ao hist贸rico
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Escanear o hist贸rico inteiro usando TruffleHog
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3.83.7
        with:
          scan: git # Analisar hist贸rico Git completo

      # Escanear apenas o diff entre base e head
      - name: Scan Push or PR Diff
        uses: trufflesecurity/trufflehog@v3.83.7
        with:
          base: ${{ github.event.before }} # Commit base para o diff
          head: ${{ github.sha }} # Commit head para o diff
