name: Secret Scan

on: [push, pull_request]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run truffleHog to scan for secrets
        uses: trufflesecurity/trufflehog-actions-scan@v3
